# Generated by Django 4.2.7 on 2023-11-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix_normal', models.FloatField()),
                ('prix_promo', models.FloatField()),
                ('description', models.TextField(default='')),
                ('caracteristique', models.TextField(default='')),
                ('categorie', models.CharField(choices=[('ordinateur', 'ORDINATEUR'), ('telephone', 'TELEPHONE'), ('tablette', 'TABLETTE'), ('electromenager', 'ELECTROMENAGER')], max_length=50)),
                ('image', models.ImageField(upload_to='produit')),
            ],
        ),
    ]
